services:
  postgres:
    image: postgres:15-alpine
    container_name: catnote-db
    environment:
      POSTGRES_USER: catnotepg
      POSTGRES_PASSWORD: mysecretpassword123
      POSTGRES_DB: catnote_db
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catnotepg -d catnote_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - catnote-network

volumes:
  postgres-data:

networks:
  catnote-network:
    driver: bridge